CELERY_IMPORTS:
      - moxie.places.tasks
      - moxie_food.tasks
      - mofa_places.tasks

BROKER_URL:
    redis://localhost:6379/1

## Results backend
CELERY_RESULT_BACKEND:
    redis://localhost:6379/1

SBB_IMPORT_URL:
    http://localhost:8000/example.db
