flask:
    DEBUG: True
    SECRET_KEY: 'put-your-secret-key-here'
    DEFAULT_ALLOW_ORIGINS:
        - 'http://localhost'
    # Places
    OSM_IMPORT_URL: 'http://download.geofabrik.de/europe/switzerland-latest.osm.bz2'

    # XXX change this
    SBB_IMPORT_URL: 'http://localhost:8000/example.db'

    # Cache
    CACHE_TYPE: 'redis'
    HAL_BROWSER_REDIRECT: '/browser/'

blueprints:
    food:
        url_prefix: /food
        factory: moxie_food.create_blueprint

services:
    places:
        POIService: {}
        SearchService:
            backend_uri: 'solr+http://localhost:8080/solr/places'
        KVService:
            backend_uri: 'redis://localhost:6379/0'
    food:
        FoodService:
            providers:
                moxie_food.providers.svgroup.FhnwSvGroupFoodProvider:
                    url: 'http://fhnw.sv-group.ch/de.html'
        KVService:
            backend_uri: 'redis://localhost:6379/0'

healthchecks:
    Places search:
        moxie.core.search.SearchService:
            backend_uri: 'solr+http://localhost:8080/solr/places'
    KV service:
        moxie.core.kv.KVService:
            backend_uri: 'redis://localhost:6379/0'
